server:
  host: "127.0.0.1"
  port: 8080
  auth:
    enabled: true
    username: "admin"
    password: "changeme"

defaults:
  interval: "10s"

targets:
  - name: "Test Service"
    host: "127.0.0.1"
    checks: [ping, http]
    ports: [9999]
